### PR TITLE
fix padding for cells with unicode

### LINKED ISSUE #102: Table calculates calculates unicode string length incorrectly
Using the `terminal.PrintableTable`, cells containing unicode characters are incorrectly padded.  The visual length of a unicode character is the same as a non-unicode character, so the padding shouldn't depends on which characters set it comes from.  

**Example**
```
package main

import (
	"github.com/IBM-Cloud/ibm-cloud-cli-sdk/bluemix/terminal"
	"os"
)

func main() {
	table := terminal.NewTable(os.Stdout, []string{"name", "message", "comments"})
	table.Add("foo", "long test message", "this works fine")
	table.Add("bar", "unicode✣", "wrong indent")
	table.Print()
}
```

**Output**
image

### PR DESCRIPTION
**Pull request by chriskirkland**
Closes #102

### CODE REVIEW

File: bluemix/terminal/table.go [hunk 1]
```diff
@@ -101,27 +102,7 @@ func (t *PrintableTable) printRow(row []string) {
 func (t *PrintableTable) cellValue(col int, value string) string {
 	padding := ""
 	if col < len(t.headers)-1 {
-		padding = strings.Repeat(" ", t.maxSizes[col]-calculateStringWidth(Decolorize(value)))
+		padding = strings.Repeat(" ", t.maxSizes[col]-utf8.RuneCountInString(Decolorize(value)))
 	}
 	return fmt.Sprintf("%s%s   ", value, padding)
 }
```
Comment (weieigao) [inline bluemix/terminal/table.go]: `RuneCountInString` returns the count of runes, not their terminal width...
For example,  count of runes in `你好` is 2, but total width should be 4.

File: bluemix/terminal/table.go [hunk 2]
```diff
@@ -71,7 +72,7 @@ func (t *PrintableTable) Print() {
 
 func (t *PrintableTable) calculateMaxSize(row []string) {
 	for index, value := range row {
-		cellLength := calculateStringWidth(Decolorize(value))
+		cellLength := utf8.RuneCountInString(Decolorize(value))
```
Comment (weieigao) [inline bluemix/terminal/table.go]: `RuneCountInString` returns the count of runes, not their terminal width...
For example, count of runes in 你好 is 2, but the total width should be 4.

Comment (weieigao) [reply bluemix/terminal/table.go]: we may considering `mattn/go-runewidth`

File: bluemix/terminal/table.go [hunk 3]
```diff
@@ -111,16 +112,11 @@ func calculateStringWidth(s string) int {
...
 		if err != nil {
 			panic(fmt.Sprintf("error when calculating visible size of: %s", s))
 		}
-
-		if runeSize == 3 {
-			width += 2
-		} else {
-			width++
-		}
+		width += runewidth.RuneWidth(rn)
```
Comment (weieigao) [inline bluemix/terminal/table.go]: can simply replace with runewidth.StringWidth(s)
