### PR TITLE
Fix trailing spaces on table rows

### LINKED ISSUE #77: Excessive spaces at the end of each line
# Problem
It seems that for every line in the console output, there is two spaces at the end. This will cause problems for testing or automation scripts which uses pattern matching (like regular expression).
image

### PR DESCRIPTION
**Pull request by brackendawson**
Fixes #77

### CODE REVIEW

File: bluemix/terminal/table.go [hunk 1]
```diff
@@ -108,10 +114,10 @@ func (t *PrintableTable) printRow(row []string) {
 
 func (t *PrintableTable) cellValue(col int, value string) string {
 	padding := ""
-	if col < len(t.headers)-1 {
```
Comment (steveclay) [inline bluemix/terminal/table.go:111]: maxSizes is more fluid than the headers, I don't think we want to change this.

Comment (brackendawson) [reply bluemix/terminal/table.go:111]: This is necessary for headerless tables where the only reliable count of the number of columns is the length of maxSizes. Would a rename of the var to something like `maxColumnLengths` make you more comfortable?

Comment (Aerex) [reply bluemix/terminal/table.go:111]: Agreed. `maxSizes` can grow based on the number of rows added and not col which may give different results as the table grows. Lets revert this change.

**Review by Aerex — COMMENTED** [review]
Runs well except lets revert the change mentioned by @steveclay. I tested it locally with the reverted commit and it works fine.

File: bluemix/terminal/table.go (hunk 1 above)
Comment (brackendawson) [reply bluemix/terminal/table.go:111]: What should be done about [this use case](https://github.com/IBM-Cloud/ibm-cloud-cli-sdk/blob/7d34e511990ecbc0c62c08ee55305d3841e2b552/bluemix/terminal/table_test.go#L52-L59)? It appears to be a supported use case as there is a test to fix the behaviour, but reverting this line as you suggest will remove all padding from between the columns, which is clearly not okay.

Comment (Aerex) [reply bluemix/terminal/table.go:111]: Yeah I see your point here. I think the change is fine here since the padding should be dependent on the number of rows added. Headers are optional which shouldn't be coupled effect if padding should be added. Thoughts @steveclay

Comment (steveclay) [reply bluemix/terminal/table.go:111]: I did not recall a headerless scenario. That is not something that would pass CLI standards for the user interface, but is apparently allowed in the code. I think this change is fine, therefore.

**Review by steveclay — DISMISSED** [review]

**Comment by steveclay** [comment]
@brackendawson can you create this PR against the `dev` branch?

**Comment by brackendawson** [comment]
Target branch in this PR changed to `dev`

**Review by steveclay — APPROVED** [review]

**Review by Aerex — APPROVED** [review]

**Comment by steveclay** [comment]
Looks like both builds passed, but the status didn't update here. Merging.
